packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - argon2
allowBuilds:
  '@scarf/scarf': set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: set this to true or false
